name: Fetch API Data

on:
  workflow_dispatch:   # allow manual runs
  schedule:
    - cron: "0 * * * *"   # runs every hour (optional, adjust as needed)

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch messages from AI API   # <-- replace old curl step with this
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          mkdir -p data
          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=$API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"contents":[{"parts":[{"text":"Generate 5 chat messages as JSON with username and message fields"}]}]}')
          MESSAGES=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          echo "$MESSAGES" | jq '.' > data/latest.json || echo '[]' > data/latest.json

      - name: Commit and push data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/latest.json
          git commit -m "Update API data [skip ci]" || echo "No changes to commit"
          git push
