- name: Fetch messages from AI API
  env:
    API_KEY: ${{ secrets.MY_API_KEY }}
  run: |
    mkdir -p data

    PERSONALITIES=$(jq -r 'to_entries | map("\(.key): \(.value)") | join("\n")' data/personalities.json)

    RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=$API_KEY" \
      -H "Content-Type: application/json" \
      -d "{
        \"contents\": [
          {
            \"parts\": [
              {
                \"text\": \"You are simulating a group chat. Each username has a distinct personality as follows:\\n\\n$PERSONALITIES\\n\\nReturn ONLY a valid JSON array of 5 chat messages. Each object must have 'username' and 'message' fields. Use only these usernames: Doo Dah, Randall, John, Fuzzy, Craig, Sherry, Albert, Long Duk Dong, AI, T-800, Yoda, Mister Brightside, Veronica. Do not include extra text, explanations, or markdown.\"
              }
            ]
          }
        ]
      }")

    echo "RAW RESPONSE:"
    echo "$RESPONSE"

    MESSAGES=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
    echo "$MESSAGES" | jq '.' > data/latest.json || echo '[]' > data/latest.json
