name: Fetch API Data

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Gemini API and update latest.json
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          mkdir -p data
          RESPONSE=$(curl -s -L \
            -H "Content-Type: application/json" \
            -H "x-goog-api-key: $GEMINI_API_KEY" \
            -d '{
              "contents": [{
                "parts":[{"text":"Give me 3 short funny chatbot-style responses"}]
              }]
            }' \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent")

          if echo "$RESPONSE" | jq . >/dev/null 2>&1; then
            echo "$RESPONSE" > data/latest.json
          else
            echo "[]" > data/latest.json
            echo "⚠️ Gemini API did not return valid JSON, wrote empty array instead."
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          git commit -m "Update latest.json [skip ci]" || echo "No changes to commit"
          git push
