name: Fetch FuzzFeed Chat Messages

on:
  workflow_dispatch:        # manual trigger
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch messages from AI API
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data

          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=$API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
                  "contents": [
                    {
                      "parts": [
                        {
                          "text": "Return ONLY a valid JSON array of 5 chat messages. Each object must have \"username\" and \"message\" fields. Only output JSON, no explanations or markdown."
                        }
                      ]
                    }
                  ]
                }')

          echo "RAW RESPONSE:"
          echo "$RESPONSE"

          # Extract the model's JSON string safely
          RAW=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text // ""')

          # Decode it into a proper JSON array (or fallback to empty array)
          echo "$RAW" | jq '.' > data/latest.json || echo '[]' > data/latest.json

      - name: Commit and push latest.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update latest.json [skip ci]"
            git push origin main
          else
            echo "No changes to commit"
          fi
