name: Fetch API Data

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

permissions:
  contents: write   # allow workflow to push changes

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch API and update latest.json
        run: |
          mkdir -p data
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_API_KEY }}" "https://api.your-service.com/messages")
          if echo "$RESPONSE" | jq . >/dev/null 2>&1; then
            echo "$RESPONSE" > data/latest.json
          else
            echo "[]" > data/latest.json
            echo "⚠️ API did not return valid JSON, wrote empty array instead."
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          git commit -m "Update latest.json [skip ci]" || echo "No changes to commit"
          git push
